Fix getopts bugs, add modelines/fix indentation when necessary.
Many programs handled missing arguments incorrectly.
Obviously the option can't be in $option if the case statement
told us $option is ':'!

Indentation in these files is inconsistent.  I tried to follow
the most common style in each file and add a modeline accordingly.
Consider doing a big cleanup later.

diff --git a/cleansvn b/cleansvn
--- a/cleansvn
+++ b/cleansvn
@@ -36,17 +36,38 @@ quiet=false
 simulate=false
 verbose=false
 
+usage()
+{
+	echo "Usage: cleansvn [-h] [-n] [-v]" 1>&2
+}
+
 # command line options
-while getopts ":nv" opt; do
-	case "$opt" in
+while getopts ":hnv" option; do
+	case "$option" in
+	h)
+		usage
+		exit 0
+		;;
 	n)
 		simulate=true
 		;;
 	v)
 		verbose=true
 		;;
+	':')
+		error "Missing argument to -$OPTARG"
+		usage
+		exit 2
+		;;
+	'?')
+		error "Unknown option -$OPTARG"
+		usage
+		exit 2
+		;;
 	*)
-		error "Invalid option $OPTARG" 1>&2
+		error "The -$option option is not supported yet" 1>&2
+		usage
+		exit 2
 		;;
 	esac
 done
@@ -66,3 +87,5 @@ for file in $(get_changed_files); do
 		error "Error removing $file"
 	fi
 done
+
+# vim: set ts=4 sw=4 tw=0 noet:
diff --git a/confdist b/confdist
--- a/confdist
+++ b/confdist
@@ -56,20 +56,41 @@ read_defaults()
 	test -f "$HOME"/.confdist && . "$HOME"/.confdist
 }
 
+usage()
+{
+	echo "Usage: confdist [-c <config file>] [-v] [<host>...]" 1>&2
+}
+
 read_options()
 {
-	while getopts ":v" flag
+	while getopts ":c:hv" flag
 	do
 		case $flag in
 		c)
 			conffile="$OPTARG"
 			;;
+		h)
+			usage
+			exit 0
+			;;
 		v)
 			verbose=$(($verbose + 1))
 			;;
-		*)
-			error "$0: Unknown option $flag"
+		':')
+			error "Missing argument to -$OPTARG"
+			usage
 			exit 2
+			;;
+		'?')
+			error "Unknown option -$OPTARG"
+			usage
+			exit 2
+			;;
+		*)
+			error "The -$flag option is not supported yet"
+			usage
+			exit 2
+			;;
 		esac
 	done
 	[ $verbose -gt 1 ] && set -x
@@ -128,3 +149,4 @@ do
 	copy_to $host && install_on $host && distribute_from $host || true
 done
 
+# vim: set ts=4 sw=4 tw=0 noet:
diff --git a/gitbackup b/gitbackup
--- a/gitbackup
+++ b/gitbackup
@@ -40,7 +40,7 @@ cleanup()
 #
 debug=
 quiet=true
-simulate=		# empty means false
+simulate=                       # empty means false
 dateformat='%-e %B %Y'
 timeformat='%H:%M:%S'
 srcroot=/home/mikelward/git
@@ -72,28 +72,28 @@ EOF
 while getopts ":hn" option
 do
     case $option in
-        h)
-            usage
-            exit 0
-            ;;
-        n)
-            simulate=true
-            ;;
-        ':')
-            echo "Missing argument to -$option" 1>&2
-            usage
-            exit 2
-            ;;
-        '?')
-            echo "Invalid option -$OPTARG" 1>&2
-            usage
-            exit 2
-            ;;
-        *)
-            echo "Program does not support -$option yet" 1>&2
-            usage
-            exit 2
-            ;;
+    h)
+        usage
+        exit 0
+        ;;
+    n)
+        simulate=true
+        ;;
+    ':')
+        echo "Missing argument to -$OPTARG" 1>&2
+        usage
+        exit 2
+        ;;
+    '?')
+        echo "Invalid option -$OPTARG" 1>&2
+        usage
+        exit 2
+        ;;
+    *)
+        echo "The -$option option is not supported yet" 1>&2
+        usage
+        exit 2
+        ;;
     esac
 done
 shift $((OPTIND - 1))
@@ -242,3 +242,4 @@ done
 
 info "Finished gitbackup on "$(date +"$dateformat")" at "$(date +"$timeformat")
 
+# vim: set ts=4 sw=4 tw=0 et:
diff --git a/gitinitremote b/gitinitremote
--- a/gitinitremote
+++ b/gitinitremote
@@ -67,7 +67,7 @@ do
 		remotename=$OPTARG
 		;;
 	':')
-		error "Missing argument to -$option"
+		error "Missing argument to -$OPTARG"
 		usage
 		exit 2
 		;;
@@ -77,7 +77,7 @@ do
 		exit 2
 		;;
 	*)
-		error "Program does not support -$option yet"
+		error "The -$option option is not supported yet"
 		usage
 		exit 2
 		;;
@@ -152,15 +152,15 @@ ssh)
 esac
 
 if ! $localalreadyrepo; then
-    # git <= 1.7 requires we have a non-empty directory for commit to work
-    # (avoid "error: pathspec '' did not match any file(s) known to git.")
-    dummyfile="$local/.gitignore"
-    if ! test -f "$dummyfile"; then
-        run touch "$dummyfile"
-    fi
-    # git add does not accept --quiet option
-    run git add "$local"                                                            || die "git add failed"
-    run git commit --quiet --message "Initial commit" "$local"                      || die "git commit failed"
+	# git <= 1.7 requires we have a non-empty directory for commit to work
+	# (avoid "error: pathspec '' did not match any file(s) known to git.")
+	dummyfile="$local/.gitignore"
+	if ! test -f "$dummyfile"; then
+		run touch "$dummyfile"
+	fi
+	# git add does not accept --quiet option
+	run git add "$local"                                                        || die "git add failed"
+	run git commit --quiet --message "Initial commit" "$local"                  || die "git commit failed"
 fi
 
 # git push does not accept --quiet option
@@ -169,3 +169,5 @@ run git push "$remotename" "$refspec"                                           
 notice "Successfully created remote $remote as $remotename"
 
 exit 0
+
+# vim: set ts=4 sw=4 tw=0 noet:
