Copy the confinst script to $HOME/bin and explicitly invoke $HOME/bin/confinst, rather than hoping confinst will be there and in the user's $PATH.

diff --git a/confdist b/confdist
--- a/confdist
+++ b/confdist
@@ -3,126 +3,110 @@
 
 error()
 {
-    echo "$@" 1>&2
+	echo "$@" 1>&2
 }
 
 run()
 {
-    if test "$simulate" -gt 0
-    then
-        echo "$@"
-    else
-        "$@"
-    fi
-    return $?
+	if test "$simulate" -gt 0
+	then
+		echo "$@"
+	else
+		"$@"
+	fi
+	return $?
 }
 
 scp()
 {
-    if test "$verbose" -gt 0
-    then
-        command scp "$@"
-    else
-        command scp "$@" 2>/dev/null
-    fi
-    return $?
+	if test "$verbose" -gt 0
+	then
+		ascp -Bq "$@"
+	else
+		ascp -Bq "$@" 2>/dev/null
+	fi
+	return $?
 }
 
 ssh()
 {
-    if test "$verbose" -gt 0
-    then
-        command ssh "$@"
-    else
-        command ssh "$@" 2>/dev/null
-    fi
-    return $?
+	if test "$verbose" -gt 0
+	then
+		assh "$@"
+	else
+		assh "$@" 2>/dev/null
+	fi
+	return $?
 }
 
 read_defaults()
 {
-    conffile="$HOME"/conf.tar.gz
-    hosts=
-    verbose=0
-    test -f "$HOME"/.confdist && . "$HOME"/.confdist
+	conffile="$HOME"/conf.tar.gz
+	hosts=
+	verbose=0
+	test -f "$HOME"/.confdist && . "$HOME"/.confdist
 }
 
 read_options()
 {
-    while getopts ":v" flag
-    do
-        case $flag in
-        c)
-            conffile="$OPTARG"
-            ;;
-        v)
-            verbose=1
-            ;;
-        *)
-            error "$0: Unknown option $flag"
-            exit 2
-        esac
-    done
+	while getopts ":v" flag
+	do
+		case $flag in
+		c)
+			conffile="$OPTARG"
+			;;
+		v)
+			verbose=1
+			;;
+		*)
+			error "$0: Unknown option $flag"
+			exit 2
+		esac
+	done
 
-    shift `expr $OPTIND - 1`
+	shift `expr $OPTIND - 1`
 
-    test $# -gt 0 && hosts="$@"
+	test $# -gt 0 && hosts="$@"
 }
-
-
 
 copy_to()
 {
-    typeset host=$1
-    printf "Copying to $host... "
-    scp $conffile $host:~
-    if test $? -ne 0
-    then
-        printf "failure\n"
-        continue
-    fi
-    printf "success\n"
+	typeset host=$1
+	printf "Copying to $host... "
+	scp $conffile $host:~
+	if test $? -ne 0
+	then
+		printf "failure\n"
+		continue
+	fi
+	printf "success\n"
 }
 
 install_on()
 {
-    typeset host=$1
-    printf "Installing on $host... "
-    ssh $host "confinst"
-    if test $? -ne 0
-    then
-        # installation script does not exist, try to install it
-        typeset destdir
-        destdir=$(ssh $host echo \$HOME/bin)
-        ssh $host test -d "$destdir"
-        if test $? -eq 0
-        then
-            ssh $host mkdir "$destdir"
-        fi
+	typeset host=$1
+	printf "Installing on $host... "
+	ssh $host "mkdir bin"
+	scp $HOME/bin/confinst $host:bin
+	if test $? -ne 0
+	then
+		printf "failure copying install script to $host:bin\n"
+		continue
+	fi
 
-        scp $(command -v confinst) "$host:$destdir"
-        if test $? -ne 0
-        then
-            printf "failure copying install script to $destdir\n"
-            continue
-        fi
-
-        ssh -v $host "$destdir/confinst"
-        if test $? -ne 0
-        then
-            printf "failure running remote install script\n"
-        else
-            printf "success\n"
-        fi
-    else
-        printf "success\n"
-    fi
+	ssh $host "bin/confinst"
+	if test $? -ne 0
+	then
+		printf "failure running remote install script\n"
+	else
+		printf "success\n"
+	fi
 }
 
 distribute_from()
 {
-    typeset host=$1
-    ssh $host confdist
+	typeset host=$1
+	ssh $host confdist
 }
 
 read_defaults
@@ -130,6 +114,6 @@ read_options "$@"
 
 for host in $hosts
 do
-    copy_to $host && install_on $host && distribute_from $host
+	copy_to $host && install_on $host && distribute_from $host
 done
 
