Make editline exit as soon as the first editor exits non-127.
This allows me to :cq in nvim and have it not try the next editor.

We can't just check if the command is available, because codeedit exists, but
exits 127 to say we should try the next editor anyway if it's not run from
inside vscode.

diff --git a/editline b/editline
--- a/editline
+++ b/editline
@@ -11,5 +11,9 @@ for arg in "$@"; do
     esac
 done
 for editor in codeedit nvimr nvim vim; do
-    "$editor" ${editor_args[$editor]} "${args[@]}" && break
+    # exit status is 127 if a command is not found
+    # codeedit returns 127 if it wants to be skipped
+    "$editor" ${editor_args[$editor]} "${args[@]}"
+    status=$?
+    test $status -ne 127 && exit $status
 done
