Only skip content at depth 1 so we can also package Mac Shortcuts, which has a directory chrome/chromeFiles/content/ that we do want in the XPI.

diff --git a/makexpi b/makexpi
--- a/makexpi
+++ b/makexpi
@@ -28,5 +28,10 @@ name=$(sed -ne '/<em:name>/ s/.*<em:name>\(.*\)<\/em:name>.*/\1/p' "$rdf")
 
 #echo "$name $version"
 xpi=$(echo "$name $version".xpi | sed -e 's/\([A-Z]\)/\l\1/g; s/ /-/g')
+if ! cd "$dir"; then
+	error "Cannot cd to $dir"
+	exit 1
+fi
+
 echo "Creating $xpi"
-prunesvn "$dir" \( -name "content" -prune \) -o \( -name "locale" -prune \) -o | zip -@ "$xpi"
+prunesvn . \( -path "./content" -prune \) -o \( -name "locale" -prune \) -o | zip -@ "$xpi"
